---
title: "R Notebook"
---

This notebook contains plots/results shared in the AAFS 2022 presentation


```{r setup}
library(tidyverse)
library(cmcR)
library(x3ptools)
source("~/cmas/cmas Functions/cmasFunctions.R")
```



```{r}
scans_notFiltered <- map(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),
                         function(file){
                           
                           dat <- x3p_read(file)
                           
                           
                           # maskBackground <- unique(c(dat$mask))[1]
                           # 
                           # if(all(str_length(unique(as.vector(dat$mask))) > 7) & !any(str_detect(unique(as.vector(dat$mask)),"FF$"))){
                           #   
                           #   maskBackground <- paste0(maskBackground,"FF")
                           #   
                           # }
                           
                           dat <- dat %>%
                             preProcess_crop(region = "exterior",
                                             radiusOffset = -30) %>%
                             preProcess_crop(region = "interior",
                                             radiusOffset = 200) %>%
                             preProcess_removeTrend(statistic = "quantile",
                                                    tau = .5,
                                                    method = "fn") %>%
                             # preProcess_gaussFilter() %>%
                             x3ptools::sample_x3p()
                           
                           # dat <- dat %>%
                           #   preProcess_cropWS(robust = FALSE,
                           #                     croppingProp = .5)
                           
                           dat$mask <- NULL
                           
                           return(dat)
                           
                         })

scans_filtered <- map(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),
                      function(file){
                        
                        dat <- x3p_read(file)
                        
                        
                        # maskBackground <- unique(c(dat$mask))[1]
                        # 
                        # if(all(str_length(unique(as.vector(dat$mask))) > 7) & !any(str_detect(unique(as.vector(dat$mask)),"FF$"))){
                        #   
                        #   maskBackground <- paste0(maskBackground,"FF")
                        #   
                        # }
                        
                        dat <- dat %>%
                          preProcess_crop(region = "exterior",
                                          radiusOffset = -30) %>%
                          preProcess_crop(region = "interior",
                                          radiusOffset = 200) %>%
                          preProcess_removeTrend(statistic = "quantile",
                                                 tau = .5,
                                                 method = "fn") %>%
                          preProcess_gaussFilter() %>%
                          x3ptools::sample_x3p()
                        
                        # dat <- dat %>%
                        #   preProcess_cropWS(robust = FALSE,
                        #                     croppingProp = .5)
                        
                        dat$mask <- NULL
                        
                        return(dat)
                        
                      })



x3pListPlot(scans_notFiltered,type = "list")
x3pListPlot(scans_filtered,type = "list")
```

```{r}
cmcR::x3pListPlot(scans_filtered[1:2],
                  rotate = c(90,90),
                  type = "list",height.colors = colorspace::desaturate(rev(c('#7f3b08','#b35806','#e08214','#fdb863','#fee0b6','#f7f7f7','#d8daeb','#b2abd2','#8073ac','#542788','#2d004b')))) %>%
  map(~ . + theme(legend.position = "none",strip.text = element_blank(),title = element_blank()))

```

```{r}
cmcR::x3pListPlot(scans_notFiltered[1:2],
                  rotate = c(90,90),
                  type = "list") %>%
  map(~ . + theme(legend.position = "none",strip.text = element_blank(),title = element_blank()))
```


```{r}
scanNames <- str_split(list.files("~/nbtrdScans/fadulScans/",full.names = TRUE,pattern = ".x3p",include.dirs = TRUE,recursive = TRUE),"/") %>%
  map_chr(~ .[[length(.)]]) %>%
  str_remove(".x3p")

# future:::ClusterRegistry("stop")

future::plan(future::multisession(workers = future::availableCores() - 10))

cmcs_notFiltered <- 
  furrr::future_map_dfr(1:(length(scans_notFiltered) - 1),
        function(refInd){
          map_dfr((refInd + 1):length(scans_notFiltered),
                  function(targInd){
                    
                    ref <- scans_notFiltered[[refInd]]
                    targ <- scans_notFiltered[[targInd]]
                    
                    CMCs <- purrr::map_dfr(seq(-30,30,by = 3),
                                           ~ comparison_allTogether(reference = ref,
                                                                    target = targ,
                                                                    theta = .))  %>%
                      mutate(originalMethodClassif = decision_CMC(cellIndex = cellIndex,
                                                                  x = x,
                                                                  y = y,
                                                                  theta = theta,
                                                                  corr = pairwiseCompCor,
                                                                  xThresh = 20,
                                                                  thetaThresh = 6,
                                                                  corrThresh = .5)) %>%
                      mutate(comparisonName = paste0(scanNames[refInd]," vs. ",scanNames[targInd]))
                    
                      return(CMCs)
                      
                  })
        })

save(cmcs_notFiltered,file = "cmcs_notFiltered.RData")

cmcs_filtered <- 
  furrr::future_map_dfr(1:(length(scans_filtered) - 1),
        function(refInd){
          map_dfr((refInd + 1):length(scans_filtered),
                  function(targInd){
                    
                    ref <- scans_filtered[[refInd]]
                    targ <- scans_filtered[[targInd]]
                    
                    CMCs <- purrr::map_dfr(seq(-30,30,by = 3),
                                           ~ comparison_allTogether(reference = ref,
                                                                    target = targ,
                                                                    theta = .))  %>%
                      mutate(originalMethodClassif = decision_CMC(cellIndex = cellIndex,
                                                                  x = x,
                                                                  y = y,
                                                                  theta = theta,
                                                                  corr = pairwiseCompCor,
                                                                  xThresh = 20,
                                                                  thetaThresh = 6,
                                                                  corrThresh = .5)) %>%
                      mutate(comparisonName = paste0(scanNames[refInd]," vs. ",scanNames[targInd]))
                    
                      return(CMCs)
                      
                  })
        })

save(cmcs_filtered,file = "cmcs_filtered.RData")
```

```{r}
matchDictionary <- map_dfr(1:10,
        function(barrel){
          
          data.frame(scanName = list.files(paste0("~/nbtrdScans/fadulScans/Fadul_",barrel),
                     pattern = ".x3p",include.dirs = FALSE,recursive = TRUE)) %>%
            mutate(scanName = str_remove(str_remove(scanName,"cc/"),".x3p"),
                   barrelName = barrel)
          
        })

cmcs_filtered <- cmcs_filtered %>%
  tidyr::separate(col = "comparisonName",
                  into = c("reference","target"),
                  sep = " vs. ",
                  remove = FALSE) %>%
  filter(reference != target)

cmcs_filtered %>%
  select(-c(refBarrel,targBarrel,type)) %>%
  left_join(matchDictionary,c("reference" = "scanName")) %>%
  rename(refBarrel = barrelName) %>%
  left_join(matchDictionary,c("target" = "scanName")) %>%
  rename(targBarrel = barrelName) %>%
  mutate(type = ifelse(refBarrel == targBarrel,"match","non-match")) %>%
  group_by(comparisonName,reference,target,refBarrel,targBarrel,type) %>%
  summarise(cmcCount = sum(originalMethodClassif == "CMC")) %>%
  group_by(type,cmcCount) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  rename(Type = type)
  ggplot(aes(x = cmcCount, y = prop)) +
  geom_bar(aes(fill = Type),stat = "identity") +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(x = "CMC Count",
       y = "Relative Frequency") +
  scale_fill_manual(values = c("#40B0A6","#E1BE6A")) +
  xlim(c(NA,25))
```

```{r}
cmcs_notFiltered <- cmcs_notFiltered %>%
  tidyr::separate(col = "comparisonName",
                  into = c("reference","target"),
                  sep = " vs. ",
                  remove = FALSE) %>%
  filter(reference != target)

cmcs_notFiltered %>%
  left_join(matchDictionary,c("reference" = "scanName")) %>%
  rename(refBarrel = barrelName) %>%
  left_join(matchDictionary,c("target" = "scanName")) %>%
  rename(targBarrel = barrelName) %>%
  mutate(type = ifelse(refBarrel == targBarrel,"match","non-match")) %>%
  group_by(comparisonName,reference,target,refBarrel,targBarrel,type) %>%
  summarise(cmcCount = sum(originalMethodClassif == "CMC")) %>%
  group_by(type,cmcCount) %>%
  tally() %>%
  mutate(prop = n/sum(n)) %>%
  rename(Type = type) %>%
  ggplot(aes(x = cmcCount, y = prop)) +
  geom_bar(aes(fill = Type),stat = "identity") +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(x = "CMC Count",
       y = "Relative Frequency") +
  scale_fill_manual(values = c("#40B0A6","#E1BE6A")) +
  xlim(c(NA,25))
```

```{r}
cmcR::cmcPlot(reference = scans_filtered[[1]],
              target = scans_filtered[[2]],
              reference_v_target_CMCs = cmcs_filtered %>% 
                filter(comparisonName == "Fadul 1-1 vs. Fadul 1-2") %>%
                select(-c(reference,target)),
              x3pNames = c("Fadul 1-1","Fadul 1-2"))

cmcR::cmcPlot(reference = scans_notFiltered[[1]],
              target = scans_notFiltered[[2]],
              reference_v_target_CMCs = cmcs_notFiltered %>% 
                filter(comparisonName == "Fadul 1-1 vs. Fadul 1-2") %>%
                select(-c(reference,target)),
              x3pNames = c("Fadul 1-1","Fadul 1-2"))
```


















```{r}
comparisonFeatures_notDetrended <- purrr::map_dfr(seq(-30,30,by = 3),
                                                  ~ comparison_allTogether(reference = scansNotDetrended[[1]],
                                                                           target = scansNotDetrended[[2]],
                                                                           
                                                                           theta = .))

comparisonFeatures_detrended <- purrr::map_dfr(seq(-30,30,by = 3),
                                               ~ comparison_allTogether(reference = scansDetrended[[1]],
                                                                        target = scansDetrended[[2]],
                                                                        
                                                                        theta = .))

cmcPlot(reference = scansNotDetrended[[1]],
        target = scansNotDetrended[[2]],
        reference_v_target_CMCs = comparisonFeatures_notDetrended %>%
          mutate(originalMethodClassif = decision_CMC(cellIndex = cellIndex,
                                                      x = x,
                                                      y = y,
                                                      theta = theta,
                                                      corr = pairwiseCompCor,
                                                      xThresh = 20,
                                                      thetaThresh = 6,
                                                      corrThresh = .5)))$CMCs +
  theme(strip.text = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank())

cmcPlot(reference = scansDetrended[[1]],
        target = scansDetrended[[2]],
        reference_v_target_CMCs = comparisonFeatures_detrended %>%
          mutate(originalMethodClassif = decision_CMC(cellIndex = cellIndex,
                                                      x = x,
                                                      y = y,
                                                      theta = theta,
                                                      corr = pairwiseCompCor,
                                                      xThresh = 20,
                                                      thetaThresh = 6,
                                                      corrThresh = .5)))$CMCs +
  theme(strip.text = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank())
```

```{r}
load("~/cmcRwriteUp/Revised-Submission/data/cmcCountData.RData")

cmcCountData %>%
  filter(transThresh == 20 & thetaThresh == 6 & corThresh == .5 & decisionRule == "originalMethodCMCs" & trendRemoved)

%>%
  group_by(type) %>%
  mutate(prop = n/sum(n)) %>%
  rename(Type = type) %>%
  ggplot(aes(x = cmcCount,y = prop,fill = Type)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(x = "CMC Count",
       y = "Relative Frequency") +
  scale_fill_manual(values = c("#40B0A6","#E1BE6A")) +
  xlim(c(NA,25))

cmcCountData %>%
  filter(transThresh == 20 & thetaThresh == 6 & corThresh == .5 & decisionRule == "originalMethodCMCs" & !trendRemoved) %>%
  group_by(type) %>%
  mutate(prop = n/sum(n)) %>%
  rename(Type = type) %>%
  ggplot(aes(x = cmcCount,y = prop,fill = Type)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(x = "CMC Count",
       y = "Relative Frequency") +
  scale_fill_manual(values = c("#40B0A6","#E1BE6A")) +
  xlim(c(NA,25))
```

